name: ðŸš€ Deploy para o Servidor Plataforma Server (rsync)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Clonar RepositÃ³rio
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: ðŸ“¦ Instalar DependÃªncias
        run: npm install

      - name: ðŸ—ï¸ Build do Angular
        run: npm run build -- --configuration production

      - name: ðŸ” Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸš€ Deploy via rsync (Ignora .user.ini)
        run: |
          rsync -avz --no-times --no-perms --delete --exclude='.user.ini' dist/humanize/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/www/wwwroot/Samuel/Humanize/
